window.PRAHA_BYTY_DATA = {
  "meta": {
    "generatedAt": "2026-10-06T09:19+02:00",
    "source": "Airtable appa2Lby5vCZbdbsf / Properties tblN9zKqD4sNnTmrw",
    "filters": {
      "availability": [
        "ACTIVE VERIFIED"
      ],
      "nextAction": [
        "CALL NOW",
        "BOOK VIEWING",
        "INVESTIGATE"
      ],
      "lastVerified": "2026-10-06",
      "exclude": [
        "REMOVED / INACTIVE",
        "RESERVED",
        "UNKNOWN",
        "REJECT",
        "NONE",
        "WATCH / WAIT",
        "stale Last Verified"
      ]
    },
    "counts": {
      "coTed": 7,
      "callNow": 6,
      "bookViewing": 1,
      "investigate": 56,
      "total": 63,
      "withPhoto": 54,
      "placeholder": 9
    },
    "reverify": {
      "checkedAt": "2026-10-06T09:17+02:00",
      "checked": 77,
      "demotedRemoved": 0,
      "live": 76
    },
    "verifiedDate": "2026-10-06",
    "rules": "properties = ACTIVE VERIFIED AND Last Verified 2026-10-06 AND Next Action CALL NOW/BOOK VIEWING. investigate = ACTIVE VERIFIED AND Last Verified 2026-10-06 AND Next Action INVESTIGATE. Never REMOVED/RESERVED/UNKNOWN/REJECT/NONE/stale."
  },
  "properties": [
    {
      "id": "rec2BhuNXIQaJjmGd",
      "title": "Osiková 2+1 51,7 m² – Žižkov",
      "address": "Osiková 2539, Praha 3 – Žižkov",
      "neighborhood": "Žižkov",
      "price": 7800000,
      "ppm2": 150870,
      "dadFit": 88,
      "investment": 84,
      "nextAction": "CALL NOW",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-zizkov-osikova/4180488268",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 51.7,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "TOP DAD"
      ],
      "thumb": "thumbs/rec2BhuNXIQaJjmGd.jpg",
      "hasPhoto": true,
      "initials": "ZI"
    },
    {
      "id": "recnXXJnx6pqcEwFW",
      "title": "Litevská 2+1 58,5 m² – Vršovice",
      "address": "Litevská 1273, Praha 10 – Vršovice",
      "neighborhood": "Vršovice",
      "price": 8850000,
      "ppm2": 151282,
      "dadFit": 88,
      "investment": 84,
      "nextAction": "CALL NOW",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-vrsovice-litevska/1823084620",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": true,
      "area": 58.5,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "TOP DAD",
        "FAST TRACK"
      ],
      "thumb": "thumbs/recnXXJnx6pqcEwFW.jpg",
      "hasPhoto": true,
      "initials": "VR"
    },
    {
      "id": "rec6kLRGwlwLOnviN",
      "title": "Na Balkáně 2532 – 2+1 49 m² – Žižkov",
      "address": "Na Balkáně 2532, Praha 3 – Žižkov",
      "neighborhood": "Žižkov",
      "price": 7200000,
      "ppm2": 146939,
      "dadFit": 84,
      "investment": 86,
      "nextAction": "CALL NOW",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-zizkov-na-balkane/972435532",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 49,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "BOTH"
      ],
      "thumb": "thumbs/rec6kLRGwlwLOnviN.jpg",
      "hasPhoto": true,
      "initials": "ZI"
    },
    {
      "id": "recvmS8Su7kXwRpvU",
      "title": "Sečská 2+1 64 m² – Strašnice",
      "address": "Sečská 1846, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 7990000,
      "ppm2": 128109,
      "dadFit": 77,
      "investment": 90,
      "nextAction": "CALL NOW",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://reality.idnes.cz/detail/prodej/byt/praha-10-secska/6a82eccf992ca04f82021a76/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 64,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "TOP INVESTMENT",
        "FAST TRACK"
      ],
      "thumb": "thumbs/recvmS8Su7kXwRpvU.webp",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "recs4sSFysBucSL8o",
      "title": "Štěchovická 2+1 50 m²",
      "address": "Štěchovická, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 7280000,
      "ppm2": 147600,
      "dadFit": 79,
      "investment": 86,
      "nextAction": "CALL NOW",
      "priority": "MEDIUM",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.origo-reality.cz/nemovitost/2085005/prodej-bytu-2-1-praha-strasnice-praha-10-stechovicka-50m2",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 50,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recs4sSFysBucSL8o.webp",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "recxFeEXSWF5UsYkp",
      "title": "Černokostelecká 2+kk 52 m² – Strašnice",
      "address": "Černokostelecká, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 7350000,
      "ppm2": 141346,
      "dadFit": 74,
      "investment": 91,
      "nextAction": "CALL NOW",
      "priority": "MEDIUM",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.remax-czech.cz/reality/detail/447160/prodej-bytu-2-kk-v-osobnim-vlastnictvi-52-m2-praha-10-strasnice",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "TOP INVESTMENT",
        "FAST TRACK"
      ],
      "thumb": "thumbs/recxFeEXSWF5UsYkp.jpg",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "rec9osncwS55VpPz7",
      "title": "Nučická 2+1 70 m² – Strašnice",
      "address": "Nučická, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 8980000,
      "ppm2": 128286,
      "dadFit": 86,
      "investment": 80,
      "nextAction": "BOOK VIEWING",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-strasnice-nucicka/2451578956",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 70,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/rec9osncwS55VpPz7.jpg",
      "hasPhoto": true,
      "initials": "ST"
    }
  ],
  "investigate": [
    {
      "id": "rec8npjs3TSqOP1yC",
      "title": "Mozambická 2+1 53 m² – Vokovice",
      "address": "Mozambická, Praha 6 – Vokovice",
      "neighborhood": "Vokovice",
      "price": 7950000,
      "ppm2": 150000,
      "dadFit": 80,
      "investment": 89,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.remax-czech.cz/reality/detail/445058/prodej-bytu-2-1-v-osobnim-vlastnictvi-53-m2-praha-6-vokovice",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 53,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "BOTH"
      ],
      "thumb": "thumbs/rec8npjs3TSqOP1yC.jpg",
      "hasPhoto": true,
      "initials": "VO"
    },
    {
      "id": "recnwMxJu6MuVuGAg",
      "title": "Vladivostocká 2+kk 52.7 m²",
      "address": "Vladivostocká, Praha 10 – Vršovice",
      "neighborhood": "Vršovice",
      "price": 8790000,
      "ppm2": 166793,
      "dadFit": 88,
      "investment": 81,
      "nextAction": "INVESTIGATE",
      "priority": "MEDIUM",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://reality.idnes.cz/detail/prodej/byt/praha-10-vladivostocka/6a7df412f554e6fd980435ae/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52.7,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "TOP DAD",
        "FAST TRACK"
      ],
      "thumb": "thumbs/recnwMxJu6MuVuGAg.webp",
      "hasPhoto": true,
      "initials": "VR"
    },
    {
      "id": "recMjaLNd1xVbJyFO",
      "title": "Čihákova 2+1 53,4 m² – Libeň",
      "address": "Čihákova, Praha 9 – Libeň",
      "neighborhood": "Libeň",
      "price": 8690000,
      "ppm2": 162734,
      "dadFit": 84,
      "investment": 82,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/1028522-nabidka-prodej-bytu-cihakova-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 53.4,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recMjaLNd1xVbJyFO.jpg",
      "hasPhoto": true,
      "initials": "LI"
    },
    {
      "id": "recixHfkamjHeRMuz",
      "title": "Kaskády Barrandov XXII – byt 302/Q2",
      "address": "Kaskády Barrandov, Praha 5",
      "neighborhood": "Barrandov",
      "price": 8439549,
      "ppm2": 159840,
      "dadFit": 82,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.finep.cz/cs/byty-kaskady-barrandov-xxii/byt-302-q2",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52.8,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/recixHfkamjHeRMuz.jpg",
      "hasPhoto": true,
      "initials": "BA"
    },
    {
      "id": "rec1vHGDAsMI7HvwV",
      "title": "Ukrajinská 2+1 53 m² – Vršovice",
      "address": "Ukrajinská, Praha 10 – Vršovice",
      "neighborhood": "Vršovice",
      "price": 8300000,
      "ppm2": 156604,
      "dadFit": 84,
      "investment": 80,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://reality.idnes.cz/detail/prodej/byt/praha-10-ukrajinska/6abd04df376efab10e0cc54d/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 53,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/rec1vHGDAsMI7HvwV.webp",
      "hasPhoto": true,
      "initials": "VR"
    },
    {
      "id": "recdtKsOonlsEJ5N7",
      "title": "Kubánské náměstí 2+1 55 m² – Vršovice",
      "address": "Kubánské náměstí 1320, Praha 10 – Vršovice",
      "neighborhood": "Vršovice",
      "price": 7990000,
      "ppm2": 145273,
      "dadFit": 78,
      "investment": 86,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-vrsovice-kubanske-namesti/251977804",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 55,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recdtKsOonlsEJ5N7.jpg",
      "hasPhoto": true,
      "initials": "VR"
    },
    {
      "id": "recXlS9Jbsiu5Ks66",
      "title": "Jasmínová 2+1 53 m² – Záběhlice",
      "address": "Jasmínová, Praha 10 – Záběhlice",
      "neighborhood": "Záběhlice",
      "price": 6900000,
      "ppm2": 135849,
      "dadFit": 72,
      "investment": 89,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://realitymix.cz/detail/praha/prodej-bytu-2-1-l-s-v-puvodnim-stavu-jasminova-praha-10-8589239.html",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 53,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "TOP INVESTMENT"
      ],
      "thumb": "thumbs/recXlS9Jbsiu5Ks66.jpg",
      "hasPhoto": true,
      "initials": "ZA"
    },
    {
      "id": "rec2VQxZSGCRAvmVg",
      "title": "Kaskády Barrandov XXII – byt 211/Q2",
      "address": "Kaskády Barrandov, Praha 5",
      "neighborhood": "Barrandov",
      "price": 8453393,
      "ppm2": 161633,
      "dadFit": 78,
      "investment": 82,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.finep.cz/cs/byty-kaskady-barrandov-xxii/byt-211-q2",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52.3,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/rec2VQxZSGCRAvmVg.jpg",
      "hasPhoto": true,
      "initials": "BA"
    },
    {
      "id": "recDCCOvhqrL1hEqy",
      "title": "Kaskády Barrandov XXII – byt 207/Q2",
      "address": "Kaskády Barrandov XXII, Praha 5 – Hlubočepy",
      "neighborhood": "Barrandov / Hlubočepy",
      "price": 8454849,
      "ppm2": 163854,
      "dadFit": 78,
      "investment": 82,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.finep.cz/cs/byty-kaskady-barrandov-xxii/byt-207-q2",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 51.6,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/recDCCOvhqrL1hEqy.jpg",
      "hasPhoto": true,
      "initials": "BA"
    },
    {
      "id": "recj9S9L1Vfq07jH9",
      "title": "Práčská 2+1 52 m² – Záběhlice",
      "address": "Práčská, Praha 10 – Záběhlice",
      "neighborhood": "Záběhlice",
      "price": 8250000,
      "ppm2": 159596,
      "dadFit": 76,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/1020006-nabidka-prodej-bytu-pracska-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recj9S9L1Vfq07jH9.jpg",
      "hasPhoto": true,
      "initials": "ZA"
    },
    {
      "id": "rec7fec5PmBgxbqsH",
      "title": "Petrohradská 402 – 2+kk 52 m²",
      "address": "Petrohradská 402, Praha – Vršovice",
      "neighborhood": "Vršovice",
      "price": 8990000,
      "ppm2": 179084,
      "dadFit": 81,
      "investment": 78,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/1058614-nabidka-prodej-bytu-petrohradska-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 50.2,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/rec7fec5PmBgxbqsH.jpg",
      "hasPhoto": true,
      "initials": "VR"
    },
    {
      "id": "recSOl3fCrFCrst3q",
      "title": "Kaskády Barrandov XXII – byt 206/S",
      "address": "Kaskády Barrandov, Praha 5",
      "neighborhood": "Barrandov",
      "price": 8871335,
      "ppm2": 151366,
      "dadFit": 77,
      "investment": 82,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.finep.cz/cs/byty-kaskady-barrandov-xxii/byt-206-s",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 58.4,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/recSOl3fCrFCrst3q.png",
      "hasPhoto": true,
      "initials": "BA"
    },
    {
      "id": "rec3zqLpnW4EHwbzE",
      "title": "Limuzská 2+kk 52 m² – Strašnice",
      "address": "Limuzská, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 9250000,
      "ppm2": 177885,
      "dadFit": 82,
      "investment": 76,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.remax-czech.cz/reality/detail/447108/prodej-bytu-2-kk-v-osobnim-vlastnictvi-52-m2-praha-10-strasnice",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/rec3zqLpnW4EHwbzE.png",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "recV8YO7MfbbLpxnJ",
      "title": "Jana Želivského 1801 – 2+kk 56 m² – Žižkov",
      "address": "Jana Želivského 1801, Praha 3 – Žižkov",
      "neighborhood": "Žižkov",
      "price": 8270000,
      "ppm2": 147679,
      "dadFit": 80,
      "investment": 78,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2Bkk/praha-zizkov-jana-zelivskeho/4172267596",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 56,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recV8YO7MfbbLpxnJ.jpg",
      "hasPhoto": true,
      "initials": "ZI"
    },
    {
      "id": "recY5Opm7iqLkuifq",
      "title": "Pod Lipami 2+1 53 m² – Žižkov (rekonstrukce 2026)",
      "address": "Pod Lipami, Praha 3 – Žižkov",
      "neighborhood": "Žižkov",
      "price": 8690000,
      "ppm2": 163962,
      "dadFit": 84,
      "investment": 74,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-zizkov-pod-lipami/3559534668",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 53,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recY5Opm7iqLkuifq.jpg",
      "hasPhoto": true,
      "initials": "ZI"
    },
    {
      "id": "recb8uxMChBh5aUkW",
      "title": "Bednářská 2+1 66 m² – Libeň",
      "address": "Bednářská 1025, Praha 8 – Libeň",
      "neighborhood": "Libeň",
      "price": 8290000,
      "ppm2": 125606,
      "dadFit": 76,
      "investment": 82,
      "nextAction": "INVESTIGATE",
      "priority": "MEDIUM",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-liben-bednarska/566505548",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 66,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recb8uxMChBh5aUkW.jpg",
      "hasPhoto": true,
      "initials": "LI"
    },
    {
      "id": "recoLmr8ZcR9gQ0Nk",
      "title": "Plukovníka Mráze 2+1 67 m² – Hostivař",
      "address": "Plukovníka Mráze, Praha – Hostivař",
      "neighborhood": "Hostivař",
      "price": 7950000,
      "ppm2": 118657,
      "dadFit": 67,
      "investment": 91,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/1060219-nabidka-prodej-bytu-plukovnika-mraze-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 67,
      "disposition": "2+1",
      "useCase": [
        "Investment"
      ],
      "tags": [
        "TOP INVESTMENT"
      ],
      "thumb": "thumbs/recoLmr8ZcR9gQ0Nk.jpg",
      "hasPhoto": true,
      "initials": "HO"
    },
    {
      "id": "recuZywJrjKpY0aEy",
      "title": "Na Balkáně 2530 – 2+1 50 m² – Žižkov",
      "address": "Na Balkáně 2530, Praha 3 – Žižkov",
      "neighborhood": "Žižkov",
      "price": 7690000,
      "ppm2": 153800,
      "dadFit": 78,
      "investment": 80,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-zizkov-na-balkane/2101625676",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 50,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recuZywJrjKpY0aEy.jpg",
      "hasPhoto": true,
      "initials": "ZI"
    },
    {
      "id": "recy2sq2nKBp5Xe8k",
      "title": "Na padesátém 789 – 2+1 64 m² – Strašnice",
      "address": "Na padesátém 789, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 8350000,
      "ppm2": 130469,
      "dadFit": 78,
      "investment": 80,
      "nextAction": "INVESTIGATE",
      "priority": "MEDIUM",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-strasnice-na-padesatem/1262563404",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 64,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recy2sq2nKBp5Xe8k.jpg",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "recawLVYnHOwDaoe9",
      "title": "5. května 2+kk 54 m² – Nusle/Pankrác",
      "address": "5. května, Praha 4 – Nusle/Pankrác",
      "neighborhood": "Nusle / Pankrác",
      "price": 6990000,
      "ppm2": 147963,
      "dadFit": 68,
      "investment": 89,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/994328-nabidka-prodej-bytu-5-kvetna-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 54,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recawLVYnHOwDaoe9.jpg",
      "hasPhoto": true,
      "initials": "NU"
    },
    {
      "id": "rec1Bo9EptmRKKzaO",
      "title": "Kaskády Barrandov XXII – byt 409/S (49 m² flag)",
      "address": "Kaskády Barrandov XXII, Praha 5 – Hlubočepy",
      "neighborhood": "Barrandov / Hlubočepy",
      "price": 8379108,
      "ppm2": 170654,
      "dadFit": 76,
      "investment": 80,
      "nextAction": "INVESTIGATE",
      "priority": "MEDIUM",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.finep.cz/cs/byty-kaskady-barrandov-xxii/byt-409-s",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 49.1,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/rec1Bo9EptmRKKzaO.jpg",
      "hasPhoto": true,
      "initials": "BA"
    },
    {
      "id": "recNsECKPQx1EWFkR",
      "title": "Bělocerkevská 1302 – 2+1 51 m² – Vršovice",
      "address": "Bělocerkevská 1302, Praha 10 – Vršovice",
      "neighborhood": "Vršovice",
      "price": 7900000,
      "ppm2": 154902,
      "dadFit": 74,
      "investment": 82,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-vrsovice-belocerkevska/4108460108",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 51,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recNsECKPQx1EWFkR.jpg",
      "hasPhoto": true,
      "initials": "VR"
    },
    {
      "id": "recSNv80ZaqruxNO5",
      "title": "Loudova 2+1 61 m² – Žižkov",
      "address": "Loudova 2431, Praha 3 – Žižkov",
      "neighborhood": "Žižkov",
      "price": 8900000,
      "ppm2": 145425,
      "dadFit": 80,
      "investment": 76,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-zizkov-loudova/2988818508",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 61.2,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recSNv80ZaqruxNO5.jpg",
      "hasPhoto": true,
      "initials": "ZI"
    },
    {
      "id": "recyTl2wgUq0ZiEao",
      "title": "Jičínská 1616 – 2+1 61 m² – Žižkov (Flora)",
      "address": "Jičínská 1616, Praha 3 – Žižkov",
      "neighborhood": "Žižkov",
      "price": 8200000,
      "ppm2": 134426,
      "dadFit": 74,
      "investment": 82,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-zizkov-jicinska/4088733772",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 61,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recyTl2wgUq0ZiEao.jpg",
      "hasPhoto": true,
      "initials": "ZI"
    },
    {
      "id": "recFiSGfY5CcFdbLS",
      "title": "Zvonková 2+1 52 m² – Záběhlice",
      "address": "Zvonková, Praha 10 – Záběhlice",
      "neighborhood": "Záběhlice",
      "price": 6990000,
      "ppm2": 138462,
      "dadFit": 68,
      "investment": 87,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://reality.idnes.cz/detail/prodej/byt/praha-10-zvonkova/6a1f07f3c215212980008864/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recFiSGfY5CcFdbLS.webp",
      "hasPhoto": true,
      "initials": "ZA"
    },
    {
      "id": "rec5iOmApZP3X5iKF",
      "title": "Boleslavova – 2+1 57 m² – Nusle",
      "address": "Boleslavova, Praha 4 – Nusle",
      "neighborhood": "Nusle / Pankrác",
      "price": 8300000,
      "ppm2": 145614,
      "dadFit": 76,
      "investment": 78,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/1065384-nabidka-prodej-bytu-boleslavova-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 57,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/rec5iOmApZP3X5iKF.png",
      "hasPhoto": true,
      "initials": "NU"
    },
    {
      "id": "recgpVU7VeYcwTRcE",
      "title": "Hartigova 2456 – 2+1 53 m² – Žižkov",
      "address": "Hartigova 2456, Praha 3 – Žižkov",
      "neighborhood": "Žižkov",
      "price": 7500000,
      "ppm2": 141509,
      "dadFit": 70,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-zizkov-hartigova/815734860",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 53,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recgpVU7VeYcwTRcE.jpg",
      "hasPhoto": true,
      "initials": "ZI"
    },
    {
      "id": "rec8kFBPwfAiwiXJk",
      "title": "Štítného 2+1 59 m² – Žižkov",
      "address": "Štítného, Praha 3 – Žižkov",
      "neighborhood": "Žižkov",
      "price": 7990000,
      "ppm2": 134602,
      "dadFit": 70,
      "investment": 82,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-zizkov-stitneho/923115596",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 59.36,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/rec8kFBPwfAiwiXJk.jpg",
      "hasPhoto": true,
      "initials": "ZI"
    },
    {
      "id": "recDLW40UBx3qekjM",
      "title": "Harfa Living – byt 152-04-064",
      "address": "Harfa Living, Praha 9 – Vysočany",
      "neighborhood": "Vysočany",
      "price": 8499301,
      "ppm2": 153417,
      "dadFit": 72,
      "investment": 80,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.central-group.cz/byt-detail/152-04-064",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 55.4,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "",
      "hasPhoto": false,
      "initials": "VY"
    },
    {
      "id": "reclxQ0r3GJqI24Kh",
      "title": "Kaskády Barrandov XXII – byt 210/Q2",
      "address": "Kaskády Barrandov, Praha 5",
      "neighborhood": "Barrandov",
      "price": 8364217,
      "ppm2": 163683,
      "dadFit": 74,
      "investment": 78,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.finep.cz/cs/byty-kaskady-barrandov-xxii/byt-210-q2",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 51.1,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/reclxQ0r3GJqI24Kh.jpg",
      "hasPhoto": true,
      "initials": "BA"
    },
    {
      "id": "rec94IOptV6V1TClS",
      "title": "Bohdalecké zahrady – byt 204-02-102 (2+kk 48 m²) – Michle (NEW BUILD)",
      "address": "Bohdalecké zahrady, Praha 4 – Michle (u Vršovic)",
      "neighborhood": "Michle",
      "price": 8528979,
      "ppm2": 176950,
      "dadFit": 72,
      "investment": 78,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.central-group.cz/byt-detail/204-02-102",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 48.2,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "",
      "hasPhoto": false,
      "initials": "MI"
    },
    {
      "id": "recExTbLFhUTJsGQQ",
      "title": "DUETA Kamýk – byt 2021",
      "address": "Přetlucká / Kamýk, Praha 12",
      "neighborhood": "Kamýk",
      "price": 8380000,
      "ppm2": 156636,
      "dadFit": 72,
      "investment": 78,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://dueta.trigema.cz/cenik",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 53.5,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/recExTbLFhUTJsGQQ.png",
      "hasPhoto": true,
      "initials": "KA"
    },
    {
      "id": "recLTvzuAn4Yg3sP6",
      "title": "Bohdalecké zahrady – byt 204-02-100 (2+kk 52,5 m²) – Michle (NEW BUILD)",
      "address": "Bohdalecké zahrady, Praha 4 – Michle (u Vršovic)",
      "neighborhood": "Michle",
      "price": 8778291,
      "ppm2": 167206,
      "dadFit": 74,
      "investment": 76,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.central-group.cz/byt-detail/204-02-100",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52.5,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "",
      "hasPhoto": false,
      "initials": "MI"
    },
    {
      "id": "recUjnFjczmjXDvbQ",
      "title": "Rezidence K Botiči – 2+kk 47 m² – Vršovice (NEW BUILD)",
      "address": "K Botiči, Praha 10 – Vršovice",
      "neighborhood": "Vršovice",
      "price": 8525000,
      "ppm2": 182940,
      "dadFit": 76,
      "investment": 74,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/992049-nabidka-prodej-bytu-k-botici-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 46.6,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/recUjnFjczmjXDvbQ.jpg",
      "hasPhoto": true,
      "initials": "VR"
    },
    {
      "id": "recjx4cfpQlqsOwj1",
      "title": "Vrátkovská 2+1 51 m²",
      "address": "Vrátkovská, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 7299000,
      "ppm2": 147039,
      "dadFit": 65,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://reality.idnes.cz/detail/prodej/byt/praha-10-vratkovska/6a69d97f6ee27299ad0128cd/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 51,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recjx4cfpQlqsOwj1.webp",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "recg8fUnMfHPdq7z3",
      "title": "V Háji 2+1 57 m² – Holešovice",
      "address": "V Háji 1243, Praha 7 – Holešovice",
      "neighborhood": "Holešovice",
      "price": 8900000,
      "ppm2": 156140,
      "dadFit": 72,
      "investment": 76,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-holesovice-v-haji/2640851020",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 57,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recg8fUnMfHPdq7z3.jpg",
      "hasPhoto": true,
      "initials": "HO"
    },
    {
      "id": "reczknO5ojIvv2AWp",
      "title": "Na Břehu 2+kk 55 m² – Vysočany",
      "address": "Na Břehu, Praha 9 – Vysočany",
      "neighborhood": "Vysočany",
      "price": 8250000,
      "ppm2": 150000,
      "dadFit": 58,
      "investment": 90,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/1058635-nabidka-prodej-bytu-na-brehu-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 55,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/reczknO5ojIvv2AWp.jpg",
      "hasPhoto": true,
      "initials": "VY"
    },
    {
      "id": "recUJmXNu24Dd6N4Q",
      "title": "Viladomy Počernice – byt 197-07-021",
      "address": "Viladomy Počernice, Praha 9 – Dolní Počernice",
      "neighborhood": "Dolní Počernice",
      "price": 8300936,
      "ppm2": 142139,
      "dadFit": 65,
      "investment": 82,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.central-group.cz/byt-detail/197-07-021",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 58.4,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "",
      "hasPhoto": false,
      "initials": "DO"
    },
    {
      "id": "rec2woW2baHn3wLpF",
      "title": "DUETA Kamýk – byt 1037",
      "address": "Přetlucká / Kamýk, Praha 12",
      "neighborhood": "Kamýk",
      "price": 8740000,
      "ppm2": 179835,
      "dadFit": 70,
      "investment": 76,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://dueta.trigema.cz/content/files/Trigema/1037-774643c5902794750961da6f24d54f9c.pdf",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 48.6,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "",
      "hasPhoto": false,
      "initials": "KA"
    },
    {
      "id": "recOg2l42eP9RcOBx",
      "title": "KATTILA Kamýk – byt 403",
      "address": "Imrychova, Praha 12 – Kamýk",
      "neighborhood": "Kamýk",
      "price": 8659840,
      "ppm2": 173197,
      "dadFit": 70,
      "investment": 76,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.yit.cz/prodej-bytu/praha/praha-12/kattila-kamyk/pdcz102725",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 50,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "",
      "hasPhoto": false,
      "initials": "KA"
    },
    {
      "id": "recUVC17qodJAUzM3",
      "title": "Horizont Kamýk – byt HK308",
      "address": "Horizont Kamýk, Praha 12",
      "neighborhood": "Kamýk",
      "price": 8806468,
      "ppm2": 169355,
      "dadFit": 72,
      "investment": 74,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.horizontkamyk.cz/apartment/HK308",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/recUVC17qodJAUzM3.jpg",
      "hasPhoto": true,
      "initials": "KA"
    },
    {
      "id": "recfJmrHYKKr9qiKD",
      "title": "Tesla Hloubětín – byt 192-13-038",
      "address": "Tesla Hloubětín, Praha 9",
      "neighborhood": "Hloubětín",
      "price": 8601779,
      "ppm2": 162605,
      "dadFit": 68,
      "investment": 78,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.central-group.cz/byt-detail/192-13-038",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52.9,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "",
      "hasPhoto": false,
      "initials": "HL"
    },
    {
      "id": "rec9FjkQmKBI0cg0G",
      "title": "RANTA Barrandov IV – byt D 205",
      "address": "Schránilova, Praha 5 – Barrandov",
      "neighborhood": "Barrandov",
      "price": 8377600,
      "ppm2": 181727,
      "dadFit": 68,
      "investment": 74,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.yit.cz/prodej-bytu/praha/praha-5/ranta-barrandov-iv/pdcz103886",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 46.1,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "",
      "hasPhoto": false,
      "initials": "BA"
    },
    {
      "id": "recVEehStbRFQh0JF",
      "title": "Místecká 2+1 56 m² – Letňany",
      "address": "Místecká, Praha 9 – Letňany",
      "neighborhood": "Letňany",
      "price": 7990000,
      "ppm2": 142679,
      "dadFit": 58,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-letnany-mistecka/1482371148",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 56,
      "disposition": "2+1",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recVEehStbRFQh0JF.jpg",
      "hasPhoto": true,
      "initials": "LE"
    },
    {
      "id": "rec4K38LatoEM7vUA",
      "title": "Kolben Gate Hindlova 2+kk 60 m² – Vysočany",
      "address": "Hindlova, Praha 9 – Vysočany (Kolben Gate)",
      "neighborhood": "Vysočany",
      "price": 8990000,
      "ppm2": 150586,
      "dadFit": 66,
      "investment": 74,
      "nextAction": "INVESTIGATE",
      "priority": "MEDIUM",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2Bkk/praha-vysocany-hindlova/4201979980",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 59.7,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/rec4K38LatoEM7vUA.jpg",
      "hasPhoto": true,
      "initials": "VY"
    },
    {
      "id": "recMahOVInmyfsu8W",
      "title": "Sportovní 2+kk 65 m² – Vršovice (rented)",
      "address": "Sportovní 823, Praha 10 – Vršovice",
      "neighborhood": "Vršovice",
      "price": 8499000,
      "ppm2": 130754,
      "dadFit": 55,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2Bkk/praha-vrsovice-sportovni/2150117452",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 65,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [
        "TOP INVESTMENT"
      ],
      "thumb": "thumbs/recMahOVInmyfsu8W.jpg",
      "hasPhoto": true,
      "initials": "VR"
    },
    {
      "id": "recGaMxtQp8V6XXiK",
      "title": "KATTILA Kamýk – byt 411",
      "address": "Imrychova, Praha 12 – Kamýk",
      "neighborhood": "Kamýk",
      "price": 9170560,
      "ppm2": 178269,
      "dadFit": 58,
      "investment": 74,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.yit.cz/prodej-bytu/praha/praha-12/kattila-kamyk/pdcz102714",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 54.1,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/recGaMxtQp8V6XXiK.webp",
      "hasPhoto": true,
      "initials": "KA"
    },
    {
      "id": "recE3jwTcCy7G6zFJ",
      "title": "Vykáňská 2+kk 54,67 m² – Strašnice",
      "address": "Vykáňská 1482/7, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 6650000,
      "ppm2": 121639,
      "dadFit": 42,
      "investment": 89,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.aktivreality.cz/prodej-bytu-2-kk-praha-strasnice-prodej-bytu-2-kk-vykanska-2328",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 54.67,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recE3jwTcCy7G6zFJ.jpg",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "recvCvNZ6sxYt5m2X",
      "title": "Velebného 2+kk 56 m² – Újezd nad Lesy",
      "address": "Velebného, Praha 21 – Újezd nad Lesy",
      "neighborhood": "Újezd nad Lesy",
      "price": 7000000,
      "ppm2": 133929,
      "dadFit": 48,
      "investment": 83,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.vitio.cz/detail/2767493/prodej-bytu-2-kk-praha-ujezd-nad-lesy-velebneho-56m2",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 56,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recvCvNZ6sxYt5m2X.webp",
      "hasPhoto": true,
      "initials": "UJ"
    },
    {
      "id": "recwauaJsHdlYyMAh",
      "title": "Chotutická 2+1 55 m² – Malešice",
      "address": "Chotutická, Praha 10 – Malešice",
      "neighborhood": "Malešice",
      "price": 7500000,
      "ppm2": 136364,
      "dadFit": 50,
      "investment": 80,
      "nextAction": "INVESTIGATE",
      "priority": "MEDIUM",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-malesice-chotuticka/2150727756",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 55,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recwauaJsHdlYyMAh.jpg",
      "hasPhoto": true,
      "initials": "MA"
    },
    {
      "id": "recxkvVEdEmrsBZTD",
      "title": "Na Balkáně mezonet 2+1 69 m² – Žižkov",
      "address": "Na Balkáně 2102, Praha 3 – Žižkov",
      "neighborhood": "Žižkov",
      "price": 7999000,
      "ppm2": 115760,
      "dadFit": 52,
      "investment": 78,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-zizkov-na-balkane/2409345100",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 69.1,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recxkvVEdEmrsBZTD.jpg",
      "hasPhoto": true,
      "initials": "ZI"
    },
    {
      "id": "recPuvS7IMgOA3Ap0",
      "title": "Sněženková 2+1 59 m² – Záběhlice",
      "address": "Sněženková, Praha 10 – Záběhlice",
      "neighborhood": "Záběhlice",
      "price": 6490000,
      "ppm2": 118475,
      "dadFit": 42,
      "investment": 85,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.mmreality.cz/nemovitosti/950545/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 59,
      "disposition": "2+1",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recPuvS7IMgOA3Ap0.jpg",
      "hasPhoto": true,
      "initials": "ZA"
    },
    {
      "id": "recrEbhUPqthGFRVr",
      "title": "Kukelská 2+kk 48,5 m²",
      "address": "Kukelská 903, Praha 9 – Hloubětín",
      "neighborhood": "Hloubětín",
      "price": 6990000,
      "ppm2": 144124,
      "dadFit": 38,
      "investment": 86,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://realitymix.cz/detail/praha/prodej-bytu-2-kk-48-5-m-lodzie-praha-ul-kukelska-8679581.html",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 48.5,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recrEbhUPqthGFRVr.jpg",
      "hasPhoto": true,
      "initials": "HL"
    },
    {
      "id": "recH3uu0o1XlxlfNV",
      "title": "Viladomy Pitkovice – byt 194-13-007",
      "address": "Viladomy Pitkovice, Praha 10",
      "neighborhood": "Pitkovice",
      "price": 8221158,
      "ppm2": 133460,
      "dadFit": 35,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.central-group.cz/byt-detail/194-13-007",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 61.6,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [
        "NEW BUILD",
        "TOP INVESTMENT"
      ],
      "thumb": "",
      "hasPhoto": false,
      "initials": "PI"
    },
    {
      "id": "receJPIbBKE5KiPAe",
      "title": "Neapolská 2+kk 43 m² – Horní Měcholupy",
      "address": "Neapolská, Praha 15 – Horní Měcholupy",
      "neighborhood": "Horní Měcholupy",
      "price": 6450000,
      "ppm2": 150000,
      "dadFit": 32,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.remax-czech.cz/reality/detail/446859/prodej-bytu-2-kk-v-osobnim-vlastnictvi-43-m2-praha-10-horni-mecholupy",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 43,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/receJPIbBKE5KiPAe.jpg",
      "hasPhoto": true,
      "initials": "HO"
    },
    {
      "id": "reczI0SeIVmSjdtQ4",
      "title": "VANAJA Kladno – byt G1 302",
      "address": "Unhošťská, Kladno",
      "neighborhood": "Kladno",
      "price": 7404320,
      "ppm2": 140233,
      "dadFit": 25,
      "investment": 80,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-06T09:17:00+02:00",
      "lastVerifiedLabel": "06.10.2026 09:17",
      "url": "https://www.yit.cz/prodej-bytu/kladno/virta-kladno/vanaja/pdcz104097",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52.8,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [
        "NEW BUILD",
        "TOP INVESTMENT"
      ],
      "thumb": "thumbs/reczI0SeIVmSjdtQ4.webp",
      "hasPhoto": true,
      "initials": "KL"
    }
  ]
};
