window.PRAHA_BYTY_DATA = {
  "meta": {
    "generatedAt": "2026-10-05T14:50+02:00",
    "source": "Airtable appa2Lby5vCZbdbsf / Properties tblN9zKqD4sNnTmrw",
    "filters": {
      "availability": [
        "ACTIVE VERIFIED"
      ],
      "nextAction": [
        "CALL NOW",
        "BOOK VIEWING",
        "INVESTIGATE"
      ],
      "lastVerified": "2026-10-05",
      "exclude": [
        "REMOVED / INACTIVE",
        "RESERVED",
        "UNKNOWN",
        "REJECT",
        "NONE",
        "WATCH / WAIT",
        "stale Last Verified"
      ]
    },
    "counts": {
      "coTed": 4,
      "callNow": 4,
      "bookViewing": 0,
      "investigate": 23,
      "total": 27,
      "withPhoto": 27,
      "placeholder": 0
    },
    "reverify": {
      "checkedAt": "2026-10-05T14:41+02:00",
      "checked": 67,
      "demotedRemoved": 26,
      "live": 41
    },
    "verifiedDate": "2026-10-05",
    "rules": "properties = ACTIVE VERIFIED AND Last Verified 2026-10-05 AND Next Action CALL NOW/BOOK VIEWING. investigate = ACTIVE VERIFIED AND Last Verified 2026-10-05 AND Next Action INVESTIGATE. Never REMOVED/RESERVED/UNKNOWN/REJECT/NONE/stale."
  },
  "properties": [
    {
      "id": "recnXXJnx6pqcEwFW",
      "title": "Litevská 2+1 58,5 m² – Vršovice",
      "address": "Litevská 1273, Praha 10 – Vršovice",
      "neighborhood": "Vršovice",
      "price": 8950000,
      "ppm2": 152991,
      "dadFit": 88,
      "investment": 84,
      "nextAction": "CALL NOW",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.reality.cz/FGB-001323/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 58.5,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "TOP DAD",
        "FAST TRACK"
      ],
      "thumb": "thumbs/recnXXJnx6pqcEwFW.jpg",
      "hasPhoto": true,
      "initials": "VR"
    },
    {
      "id": "recs4sSFysBucSL8o",
      "title": "Štěchovická 2+1 50 m²",
      "address": "Štěchovická, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 7280000,
      "ppm2": 145600,
      "dadFit": 79,
      "investment": 86,
      "nextAction": "CALL NOW",
      "priority": "MEDIUM",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.origo-reality.cz/nemovitost/2085005/prodej-bytu-2-1-praha-strasnice-praha-10-stechovicka-50m2",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 50,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recs4sSFysBucSL8o.webp",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "recvmS8Su7kXwRpvU",
      "title": "Sečská 2+1 64 m² – Strašnice",
      "address": "Sečská 1846, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 7990000,
      "ppm2": 124844,
      "dadFit": 77,
      "investment": 90,
      "nextAction": "CALL NOW",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://reality.idnes.cz/detail/prodej/byt/praha-10-secska/6a82eccf992ca04f82021a76/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 64,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "TOP INVESTMENT",
        "FAST TRACK"
      ],
      "thumb": "thumbs/recvmS8Su7kXwRpvU.webp",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "recxFeEXSWF5UsYkp",
      "title": "Černokostelecká 2+kk 52 m² – Strašnice",
      "address": "Černokostelecká, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 7350000,
      "ppm2": 141346,
      "dadFit": 74,
      "investment": 91,
      "nextAction": "CALL NOW",
      "priority": "MEDIUM",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.remax-czech.cz/reality/detail/447160/prodej-bytu-2-kk-v-osobnim-vlastnictvi-52-m2-praha-10-strasnice",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "TOP INVESTMENT",
        "FAST TRACK"
      ],
      "thumb": "thumbs/recxFeEXSWF5UsYkp.jpg",
      "hasPhoto": true,
      "initials": "ST"
    }
  ],
  "investigate": [
    {
      "id": "recnwMxJu6MuVuGAg",
      "title": "Vladivostocká 2+kk 52.7 m²",
      "address": "Vladivostocká, Praha 10 – Vršovice",
      "neighborhood": "Vršovice",
      "price": 8790000,
      "ppm2": 166793,
      "dadFit": 88,
      "investment": 81,
      "nextAction": "INVESTIGATE",
      "priority": "MEDIUM",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://reality.idnes.cz/detail/prodej/byt/praha-10-vladivostocka/6a7df412f554e6fd980435ae/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52.7,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "TOP DAD",
        "FAST TRACK"
      ],
      "thumb": "thumbs/recnwMxJu6MuVuGAg.webp",
      "hasPhoto": true,
      "initials": "VR"
    },
    {
      "id": "recMjaLNd1xVbJyFO",
      "title": "Čihákova 2+1 53,4 m² – Libeň",
      "address": "Čihákova, Praha 9 – Libeň",
      "neighborhood": "Libeň",
      "price": 8690000,
      "ppm2": 162734,
      "dadFit": 84,
      "investment": 82,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/1028522-nabidka-prodej-bytu-cihakova-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 53.4,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recMjaLNd1xVbJyFO.jpg",
      "hasPhoto": true,
      "initials": "LI"
    },
    {
      "id": "rec3zqLpnW4EHwbzE",
      "title": "Limuzská 2+kk 52 m² – Strašnice",
      "address": "Limuzská, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 9250000,
      "ppm2": 177885,
      "dadFit": 82,
      "investment": 76,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.remax-czech.cz/reality/detail/447108/prodej-bytu-2-kk-v-osobnim-vlastnictvi-52-m2-praha-10-strasnice",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/rec3zqLpnW4EHwbzE.png",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "rec7fec5PmBgxbqsH",
      "title": "Petrohradská 402 – 2+kk 52 m²",
      "address": "Petrohradská 402, Praha – Vršovice",
      "neighborhood": "Vršovice",
      "price": 8990000,
      "ppm2": 179084,
      "dadFit": 81,
      "investment": 78,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/1058614-nabidka-prodej-bytu-petrohradska-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 50.2,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/rec7fec5PmBgxbqsH.jpg",
      "hasPhoto": true,
      "initials": "VR"
    },
    {
      "id": "rec8npjs3TSqOP1yC",
      "title": "Mozambická 2+1 53 m² – Vokovice",
      "address": "Mozambická, Praha 6 – Vokovice",
      "neighborhood": "Vokovice",
      "price": 7950000,
      "ppm2": 150000,
      "dadFit": 80,
      "investment": 89,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.remax-czech.cz/reality/detail/445058/prodej-bytu-2-1-v-osobnim-vlastnictvi-53-m2-praha-6-vokovice",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 53,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "BOTH"
      ],
      "thumb": "thumbs/rec8npjs3TSqOP1yC.jpg",
      "hasPhoto": true,
      "initials": "VO"
    },
    {
      "id": "recSOl3fCrFCrst3q",
      "title": "Kaskády Barrandov XXII – byt 206/S",
      "address": "Kaskády Barrandov, Praha 5",
      "neighborhood": "Barrandov",
      "price": 8871335,
      "ppm2": 151906,
      "dadFit": 77,
      "investment": 82,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.finep.cz/cs/byty-kaskady-barrandov-xxii/byt-206-s",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 58.4,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/recSOl3fCrFCrst3q.png",
      "hasPhoto": true,
      "initials": "BA"
    },
    {
      "id": "recj9S9L1Vfq07jH9",
      "title": "Práčská 2+1 52 m² – Záběhlice",
      "address": "Práčská, Praha 10 – Záběhlice",
      "neighborhood": "Záběhlice",
      "price": 8250000,
      "ppm2": 158654,
      "dadFit": 76,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/1020006-nabidka-prodej-bytu-pracska-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recj9S9L1Vfq07jH9.jpg",
      "hasPhoto": true,
      "initials": "ZÁ"
    },
    {
      "id": "recXlS9Jbsiu5Ks66",
      "title": "Jasmínová 2+1 53 m² – Záběhlice",
      "address": "Jasmínová, Praha 10 – Záběhlice",
      "neighborhood": "Záběhlice",
      "price": 6900000,
      "ppm2": 130189,
      "dadFit": 72,
      "investment": 89,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://realitymix.cz/detail/praha/prodej-bytu-2-1-l-s-v-puvodnim-stavu-jasminova-praha-10-8589239.html",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 53,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [
        "TOP INVESTMENT"
      ],
      "thumb": "thumbs/recXlS9Jbsiu5Ks66.jpg",
      "hasPhoto": true,
      "initials": "ZÁ"
    },
    {
      "id": "recFiSGfY5CcFdbLS",
      "title": "Zvonková 2+1 52 m² – Záběhlice",
      "address": "Zvonková, Praha 10 – Záběhlice",
      "neighborhood": "Záběhlice",
      "price": 6990000,
      "ppm2": 134423,
      "dadFit": 68,
      "investment": 87,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://reality.idnes.cz/detail/prodej/byt/praha-10-zvonkova/6a1f07f3c215212980008864/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recFiSGfY5CcFdbLS.webp",
      "hasPhoto": true,
      "initials": "ZÁ"
    },
    {
      "id": "recawLVYnHOwDaoe9",
      "title": "5. května 2+kk 54 m² – Nusle/Pankrác",
      "address": "5. května, Praha 4 – Nusle/Pankrác",
      "neighborhood": "Nusle / Pankrác",
      "price": 6990000,
      "ppm2": 129444,
      "dadFit": 68,
      "investment": 89,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/994328-nabidka-prodej-bytu-5-kvetna-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 54,
      "disposition": "2+kk",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recawLVYnHOwDaoe9.jpg",
      "hasPhoto": true,
      "initials": "NP"
    },
    {
      "id": "recoLmr8ZcR9gQ0Nk",
      "title": "Plukovníka Mráze 2+1 67 m² – Hostivař",
      "address": "Plukovníka Mráze, Praha – Hostivař",
      "neighborhood": "Hostivař",
      "price": 7950000,
      "ppm2": 118657,
      "dadFit": 67,
      "investment": 91,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/1060219-nabidka-prodej-bytu-plukovnika-mraze-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 67,
      "disposition": "2+1",
      "useCase": [
        "Investment"
      ],
      "tags": [
        "TOP INVESTMENT"
      ],
      "thumb": "thumbs/recoLmr8ZcR9gQ0Nk.jpg",
      "hasPhoto": true,
      "initials": "HO"
    },
    {
      "id": "recjx4cfpQlqsOwj1",
      "title": "Vrátkovská 2+1 51 m²",
      "address": "Vrátkovská, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 7299000,
      "ppm2": 143118,
      "dadFit": 65,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://reality.idnes.cz/detail/prodej/byt/praha-10-vratkovska/6a69d97f6ee27299ad0128cd/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 51,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recjx4cfpQlqsOwj1.webp",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "recVEehStbRFQh0JF",
      "title": "Místecká 2+1 56 m² – Letňany",
      "address": "Místecká, Praha 9 – Letňany",
      "neighborhood": "Letňany",
      "price": 7990000,
      "ppm2": 142679,
      "dadFit": 58,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.sreality.cz/detail/prodej/byt/2%2B1/praha-letnany-mistecka/1482371148",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 56,
      "disposition": "2+1",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recVEehStbRFQh0JF.jpg",
      "hasPhoto": true,
      "initials": "LE"
    },
    {
      "id": "reczknO5ojIvv2AWp",
      "title": "Na Břehu 2+kk 55 m² – Vysočany",
      "address": "Na Břehu, Praha 9 – Vysočany",
      "neighborhood": "Vysočany",
      "price": 8250000,
      "ppm2": 150000,
      "dadFit": 58,
      "investment": 90,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.bezrealitky.cz/nemovitosti-byty-domy/1058635-nabidka-prodej-bytu-na-brehu-praha",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 55,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/reczknO5ojIvv2AWp.jpg",
      "hasPhoto": true,
      "initials": "VY"
    },
    {
      "id": "recGaMxtQp8V6XXiK",
      "title": "KATTILA Kamýk – byt 411",
      "address": "Imrychova, Praha 12 – Kamýk",
      "neighborhood": "Kamýk",
      "price": 9170560,
      "ppm2": 169511,
      "dadFit": 58,
      "investment": 74,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.yit.cz/prodej-bytu/praha/praha-12/kattila-kamyk/pdcz102714",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 54.1,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [
        "NEW BUILD"
      ],
      "thumb": "thumbs/recGaMxtQp8V6XXiK.webp",
      "hasPhoto": true,
      "initials": "KA"
    },
    {
      "id": "recvCvNZ6sxYt5m2X",
      "title": "Velebného 2+kk 56 m² – Újezd nad Lesy",
      "address": "Velebného, Praha 21 – Újezd nad Lesy",
      "neighborhood": "Újezd nad Lesy",
      "price": 7000000,
      "ppm2": 125000,
      "dadFit": 48,
      "investment": 83,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.vitio.cz/detail/2767493/prodej-bytu-2-kk-praha-ujezd-nad-lesy-velebneho-56m2",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 56,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recvCvNZ6sxYt5m2X.webp",
      "hasPhoto": true,
      "initials": "ÚN"
    },
    {
      "id": "recPuvS7IMgOA3Ap0",
      "title": "Sněženková 2+1 59 m² – Záběhlice",
      "address": "Sněženková, Praha 10 – Záběhlice",
      "neighborhood": "Záběhlice",
      "price": 6490000,
      "ppm2": 110000,
      "dadFit": 42,
      "investment": 85,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.mmreality.cz/nemovitosti/950545/",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 59,
      "disposition": "2+1",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recPuvS7IMgOA3Ap0.jpg",
      "hasPhoto": true,
      "initials": "ZÁ"
    },
    {
      "id": "recE3jwTcCy7G6zFJ",
      "title": "Vykáňská 2+kk 54,67 m² – Strašnice",
      "address": "Vykáňská 1482/7, Praha 10 – Strašnice",
      "neighborhood": "Strašnice",
      "price": 6650000,
      "ppm2": 121639,
      "dadFit": 42,
      "investment": 89,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.aktivreality.cz/prodej-bytu-2-kk-praha-strasnice-prodej-bytu-2-kk-vykanska-2328",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 54.67,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recE3jwTcCy7G6zFJ.jpg",
      "hasPhoto": true,
      "initials": "ST"
    },
    {
      "id": "recrEbhUPqthGFRVr",
      "title": "Kukelská 2+kk 48,5 m²",
      "address": "Kukelská 903, Praha 9 – Hloubětín",
      "neighborhood": "Hloubětín",
      "price": 6990000,
      "ppm2": 144124,
      "dadFit": 38,
      "investment": 86,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://realitymix.cz/detail/praha/prodej-bytu-2-kk-48-5-m-lodzie-praha-ul-kukelska-8679581.html",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 48.5,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recrEbhUPqthGFRVr.jpg",
      "hasPhoto": true,
      "initials": "HL"
    },
    {
      "id": "receJPIbBKE5KiPAe",
      "title": "Neapolská 2+kk 43 m² – Horní Měcholupy",
      "address": "Neapolská, Praha 15 – Horní Měcholupy",
      "neighborhood": "Horní Měcholupy",
      "price": 6450000,
      "ppm2": 150000,
      "dadFit": 32,
      "investment": 84,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.remax-czech.cz/reality/detail/446859/prodej-bytu-2-kk-v-osobnim-vlastnictvi-43-m2-praha-10-horni-mecholupy",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 43,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/receJPIbBKE5KiPAe.jpg",
      "hasPhoto": true,
      "initials": "HM"
    },
    {
      "id": "reczI0SeIVmSjdtQ4",
      "title": "VANAJA Kladno – byt G1 302",
      "address": "Unhošťská, Kladno",
      "neighborhood": "Kladno",
      "price": 7404320,
      "ppm2": 140233,
      "dadFit": 25,
      "investment": 80,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.yit.cz/prodej-bytu/kladno/virta-kladno/vanaja/pdcz104097",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 52.8,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [
        "NEW BUILD",
        "TOP INVESTMENT"
      ],
      "thumb": "thumbs/reczI0SeIVmSjdtQ4.webp",
      "hasPhoto": true,
      "initials": "KL"
    },
    {
      "id": "recFSnVJzI4a1GaXA",
      "title": "Minická 2+kk 41 m² – Čimice",
      "address": "Minická, Praha 8 – Čimice",
      "neighborhood": "Čimice",
      "price": 5800000,
      "ppm2": 141463,
      "dadFit": 22,
      "investment": 88,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://www.origo-reality.cz/nemovitost/2151912/prodej-bytu-2-kk-praha-cimice-minicka-41m2",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 41,
      "disposition": "2+kk",
      "useCase": [
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recFSnVJzI4a1GaXA.webp",
      "hasPhoto": true,
      "initials": "ČI"
    },
    {
      "id": "recsEfO8Bcl3mEipX",
      "title": "Aubrechtové 2+1 53 m² – Záběhlice",
      "address": "Aubrechtové 3105, Praha 10 – Záběhlice",
      "neighborhood": "Záběhlice",
      "price": 6700000,
      "ppm2": 126415,
      "dadFit": null,
      "investment": null,
      "nextAction": "INVESTIGATE",
      "priority": "HIGH",
      "lastVerified": "2026-10-05T14:41:00+02:00",
      "lastVerifiedLabel": "05.10.2026 14:41",
      "url": "https://severo.ceskereality.cz/prodej/byty/byty-2-1/praha/prodej-bytu-2-1-53-m2-aubrechtove-3799419.html",
      "availability": "ACTIVE VERIFIED",
      "priceDrop": false,
      "area": 53,
      "disposition": "2+1",
      "useCase": [
        "Dad",
        "Investment"
      ],
      "tags": [],
      "thumb": "thumbs/recsEfO8Bcl3mEipX.jpg",
      "hasPhoto": true,
      "initials": "Z"
    }
  ]
};
